version: '1.0.{build}'
image: Visual Studio 2017
clone_depth: 1

assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
  
before_build:
    - cmd: dotnet --version
    - cmd: dotnet restore --verbosity m

build_script:
    - cmd: dotnet publish ./RBush/RBush.csproj -c Release

test_script:
    - cmd: cd RBush.Test
    - cmd: dotnet xunit
    - cmd: cd ..

after_test:
    - cmd: nuget pack ./RBush/RBush.nuspec -version %appveyor_build_version%

artifacts:
  - path: RBush\bin\Release\netstandard1.2\RBush.dll
    name: RBush.dll
  - path: '**\*.nupkg'

cache:
  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3

deploy:
    provider: NuGet
    api_key:
        secure: lGI6OxVnMUoqVp/LUY35aCtJ5ty8ByQAVDasWeoLiKjQWp5VRhK5ORqaD2ZMAmK5
    skip_symbols: true
    artifact: '**\*.nupkg'
    on: 
        branch: master
